### ISSUE TITLE
Unable to connect with TLS encryption

### ISSUE THREAD

**Issue by smercadomx** [YOzaz/Laravel-SwiftMailer#2]
I'm getting this error from time to time:

```
[2015-09-20 19:57:09] prod.ERROR: exception 'Swift_TransportException' with message 'Unable to connect with TLS encryption' in /var/www/html/backend/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php:289
Stack trace:
#0 /var/www/html/backend/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(118): Swift_Transport_EsmtpTransport->_doHeloCommand()
#1 /var/www/html/backend/vendor/yozaz/laravel-swiftmailer/src/YOzaz/LaravelSwiftmailer/Mailer.php(169): Swift_Transport_AbstractSmtpTransport->start()
#2 /var/www/html/backend/vendor/yozaz/laravel-swiftmailer/src/YOzaz/LaravelSwiftmailer/Mailer.php(197): YOzaz\LaravelSwiftmailer\Mailer->resetSwiftTransport()
#3 /var/www/html/backend/bootstrap/compiled.php(3271): YOzaz\LaravelSwiftmailer\Mailer->send('emails.vip-aler...', Array, Object(Closure))
#4 /var/www/html/backend/app/Acme/Services/EmailSenderService.php(18): Illuminate\Support\Facades\Facade::__callStatic('send', Array)
#5 /var/www/html/backend/app/Acme/Services/EmailSenderService.php(18): YOzaz\LaravelSwiftmailer\Facade::send('emails.vip-aler...', Array, Object(Closure))
```

**Comment by YOzaz** [comment]
It's pretty much the same problem, like in here: https://github.com/YOzaz/Laravel-SwiftMailer/issues/1.

**Comment by ncking** [comment]
Same issues on dev machine, was due to antivirus software; Avasts MailShield protection.
Suspened this particualr filter and everyting worked as expected

**Comment by YOzaz** [comment]
Goes out of the package scope, specific to SSL certificate validation.
